# Generated by Django 5.0.7 on 2024-08-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_courselesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselesson',
            old_name='content',
            new_name='description',
        ),
    ]
