# Generated by Django 5.0.7 on 2024-08-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_course_status_enrolledcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='user',
            new_name='student',
        ),
    ]
