# Generated by Django 5.0.7 on 2024-09-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_order_oderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
