# Generated by Django 5.0.7 on 2024-09-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_order_address_order_success'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
    ]
