# Generated by Django 5.0.7 on 2025-02-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_feedback_lessonreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField(default=1)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('promo_video_url', models.URLField(blank=True, max_length=250, null=True)),
                ('organizer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_url', models.URLField(blank=True, max_length=250, null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('organizer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organizer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instructions', models.TextField(blank=True, max_length=2500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.category')),
            ],
        ),
    ]
