# Generated by Django 5.0.7 on 2025-02-17 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_event_location_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideoSubtitles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtitle', models.TextField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Tamil', 'Tamil')], default='English', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.courselesson')),
            ],
        ),
    ]
