# Generated by Django 5.0.7 on 2025-02-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_lessonvideosubtitles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonVideoSubtitles',
            new_name='LessonVideoSubtitle',
        ),
    ]
