from django.urls import path, include
from . import views
from .views import admin_view, teacher_qualification, admin_teacher_requests_view, admin_index, approval_pending, create_subcategory,view_subcategories, delete_subcategory
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('courses/', views.courses, name='courses'),
    path('category/', views.category, name='category'),
    path('events/', views.events, name='events'),
    # path('contact/', views.contact, name='contact'),
    path('contact-us/', views.contact_us, name='contact'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('admin_view/', views.admin_view, name='admin_view'),
    # path('student/', views.student, name='student'),
    path('teacher/', views.teacher, name='teacher'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('reset/<token>/', views.reset, name='reset'),
    path('teacher/qualification/', views.teacher_qualification, name='teacher_qualification'),
    path('categories/', views.view_categories, name='view_categories'),
    path('add_product_rent/', views.add_product_rent, name='add_product_rent'),
    path('add_product_buy/', views.add_product_buy, name='add_product_buy'),
    path('teacher_requests/', views.admin_teacher_requests_view, name='teacher_requests'),
    path('approve_request/<int:request_id>/', views.approve_request, name='approve_request'),
    path('reject_request/<int:request_id>/', views.reject_request, name='reject_request'),
    path('accept_teacher/', views.accept_teacher, name='accept_teacher'),
    path('reject_teacher/', views.reject_teacher, name='reject_teacher'),
    path('accounts/', include('allauth.urls')),
    path('approval_pending/', views.approval_pending, name='approval_pending'),
    path('approve_request/<int:request_id>/', views.approve_request, name='approve_request'),
    path('reject_request/<int:request_id>/', views.reject_request, name='reject_request'),
    path('add-category/', views.add_category, name='add_category'),
    path('view-categories/', views.view_categories, name='view_categories'),  # Assuming you have a view_categories view
    path('edit_category/<int:id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:id>/', views.delete_category, name='delete_category'),
    path('add_subcategory/', views.add_subcategory, name='add_subcategory'),
    path('create_subcategory/', create_subcategory, name='create_subcategory'),
    path('profile/', views.profile, name='profile'),
    path('view-subcategories/', view_subcategories, name='view_subcategories'),
    path('delete-subcategory/<int:subcategory_id>/', delete_subcategory, name='delete_subcategory'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('student-details/', views.student_details, name='student_details'),
    

    path('admin-contact/', views.admin_contact_us_view, name='admin_contact'),
    path('admin-contact-delete/<int:id>/', views.admin_delete_contact_us_view, name='admin_contact_delete'),
    path('admin-courses/', views.admin_courses_view, name='admin_courses'),
    path('admin-approve-course/<int:id>/', views.admin_approve_course, name='admin_approve_course'),
    path('admin-reject-course/<int:id>/', views.admin_reject_course, name='admin_reject_course'),
    path('admin-products/', views.admin_list_product, name='admin_list_product'),
    path('admin-product/create/', views.admin_create_product, name='admin_create_product'),
    path('admin-product/edit/<int:id>/', views.admin_edit_product, name='admin_edit_product'),
    path('admin-product/delete/<int:id>/', views.admin_delete_product, name='admin_delete_product'),
    path('admin-event/', views.EventListView.as_view(), name='admin_event'),
    path('admin-event/create/', views.EventCreateView.as_view(), name='admin_create_event'),
    path('admin-event/edit/<int:id>/', views.EventUpdateView.as_view(), name='admin_edit_event'),
    path('admin-event/delete/<int:id>/', views.admin_delete_event, name='admin_delete_event'),
    path('admin-teacher-requests/', views.admin_teacher_requests_view, name='teacher_requests'),

    path('teacher_home/', views.teacher_home, name='teacher_home'),
    path('teacher-pick-category/', views.teacher_pick_category, name='teacher_pick_category'),
    path('teacher-course-sub-category/<int:id>/', views.teacher_pick_subcategory, name='teacher_subcategory'),
    path('teacher/course/create/<int:id>/', views.teacher_create_course, name='teacher_create_course'),
    path('teacher/course/edit/<int:id>/', views.teacher_edit_course, name='teacher_edit_course'),
    path('teacher/course/delete/<int:id>/', views.teacher_delete_course, name='teacher_delete_course'),
    path('teacher/course/restore/<int:id>/', views.teacher_restore_course, name='teacher_restore_course'),
    path('teacher/course/approval/<int:id>/', views.teacher_request_course_approval, name='teacher_request_course_approval'),
    path('teacher/course/lesson/<int:id>/', views.teacher_create_course_lesson, name='teacher_create_course_lesson'),
    path('teacher/course/lesson/delete/<int:id>/', views.teacher_delete_course_lesson, name='teacher_delete_course_lesson'),
    path('teacher/course/students/<int:id>/', views.teacher_course_students, name='teacher_course_students'),
    path('teacher/live-class/', views.LiveClassListView.as_view(), name='teacher_liveclass'),
    path('teacher/live-class/create/', views.LiveClassCreateView.as_view(), name='teacher_create_liveclass'),
    path('teacher/live-class/delete/<int:id>/', views.teacher_delete_liveclass, name='teacher_delete_liveclass'),

    path('student/', views.student_home, name='student_home'),
    path('student/more-courses/', views.student_more_courses, name='student_more_courses'),
    path('student/enroll/<int:id>/', views.student_enroll, name='student_enroll'),
    path('student/view-lesson/<int:id>/', views.student_take_lesson, name='student_view_lesson'),
    path('student/subtitle/<int:id>/<str:language>/', views.student_subtitle_lesson, name='student_subtitle_lesson'),
    path('student/create-course-payment/<int:id>/', views.student_create_course_payment, name='create__course_payment'),
    path('student/enroll/success/<int:id>/', views.student_enroll_success, name='enroll_success'),
    path('student/enroll/failure/', views.student_enroll_failure, name='enroll_failure'),
    path('student/store/', views.student_store, name='student_store'),
    path('student/cart/add<int:id>/', views.student_cart_add, name='student_cart_add'),
    path('student/cart/delete/<int:id>/', views.student_cart_delete, name='student_cart_delete'),
    path('student/cart/', views.student_cart, name='student_cart'),
    path('student/checkout/', views.student_place_order, name='student_place_order'),
    path('student/checkout/payment/<int:id>/', views.student_order_payment, name='student_order_payment'),
    path('student/create-order-payment/<int:id>/', views.student_create_order_payment, name='student_order_payment'),
    path('student/orders/success/<int:id>/', views.student_order_success, name='student_order_success'),
    path('student/orders/', views.student_orders, name='student_orders'),
    path('student/events/', views.StudentEventListView.as_view(), name='student_events'),
    path('student/events/<int:id>/', views.StudentEventDetailView.as_view(), name='student_event_detail'),
    path('student/liveclass/', views.StudentLiveClassListView.as_view(), name='student_liveclass'),
    path('student/notification/', views.StudentNotificationListView.as_view(), name='student_notification'),
    path('student/certificate/<int:id>/', views.GetCertificateView.as_view(), name='student_get_certificate'),

    path('submit-feedback/<int:lesson_id>/', views.submit_feedback, name='submit_feedback'),
    path('find_art/', views.find_art, name='find_art'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
